serverless/serverless-python-requirements

index.js
@bsamuel-ui test this before I merge it?
=> Add deps to include automatically

index.js
I was fixing something CI related to this plugin for a coworker when I noticed that the log messages were backwards.
=> Fix backwards log messages

index.js, package.json
=> Create .serverless dir if necessary

README.md, index.js
=> Allow custom requirements filename. closes #51

index.js
closes #62 and  closes #21 
cc @rasterburn @AndrewFarley @ChrisAnn @FelschR
Sorry this simple fix took so long windows folks 😬
=> Only pass UID option to Docker on Linux

index.js
- Remove single quotes from key
- In this code, it seems that it is often not quoted for simple strings. I unified the format.
- Fix indent of code
- Modify let to const
- Since it does not assignment after that, it modifid to const.
- Remove unnecessary else
- Because return in the if statement.
=> Modified a few of the code formats.

index.js
Does this seem like a good approach @kennethreitz
=> Generate requirements.txt using pipenv instead of installing with pipenv

lib/pipenv.js
This addresses issue 91. Very odd.
=> Fix bug when a deploymentBucket is used

lib/pip.js
=> deal with reqs being a symlink in docker

example_native_deps/.gitignore, example_native_deps/README.md, example_native_deps/handler.py, example_native_deps/requirements.txt, example_native_deps/serverless.yml
=> Add native compilation example

lib/link.js, lib/pip.js
Fix referencing variable.
In addition, I fixed the indent.
=> Fix referencing variable

lib/pip.js
Without curly brackets it appeared not to be processed as expected.
=> Fix to add curly brackets

lib/pip.js
=> Add `const` when defining `chownCmd` variable

.eslintrc.yml, index.js, lib/docker.js
I would like to add indentation rules.
What do you think.
=>  Add indent rule to ESLint

README.md
=> README link typo

index.js
- Add function to check functionObj.runtime
- Add brace to if statement
=> Improve function runtime check

lib/docker.js
=> Reorder `bindPaths` for faster detection

README.md
=> cache spelling in README

unzip_requirements.py
=> Insert zipped packages at beginning of path #367

README.md, package.json
This is getting ready to tag and push. I haven't seen anything that requires a minor version update, so this will be a point release.
Additional QA: I tested this with a large python project, and that went through successfully.
=> Update minor version and note recent contributors.

CHANGELOG.md, package.json
Additionally bump `peerDependencies` version
=> Release v5.3.0

.github/workflows/integrate.yml, .github/workflows/validate.yml
Address the failing CI jobs on all other PRs
=> ci: Upgrade `python-setup` github action

index.js, test.js
=> fix: Properly recognize individual function

.github/workflows/integrate.yml, .github/workflows/validate.yml
=> ci: Temporarily minimize testing matrix

README.md
I haven't been the lead developer for a number of years.
=> Update the description of myself

tests/poetry/pyproject.toml, tests/poetry_individually/module1/pyproject.toml, tests/poetry_packages/pyproject.toml
Turns out that poetry was causing the slow builds due a super slow dependencies resolution process
=> ci: Pin versions to speed up poetry deps resolution

.github/workflows/publish.yml, .github/workflows/validate.yml
=> [ci] Update to Node18
