serverless/serverless-python-requirements

README.md
index.js
package.json
requirements.py

Leverages Python's [zipimport](https://docs.python.org/2.7/library/zipimport.html). Currently using github master of easy-zip, should probably be using something from NPM. 
Closes #3
@amitaymolko, thoughts? This makes the unzipped size of dependencies not count against the 250Mb deflated limit for lambdas.
todo:

Use zipped libs to deal with aws size limits

---

index.js

By default docker executes commands in an container as root. This causes the downloaded dependencies to be owned by root. This messes up cleanup scripts.
Using the correct object which holds the dockerizePip option.
this.serverless.service.custom.dockerizePip
Initialize the this.serverless.service.package.exclude and this.serverless.service.package.include correctly if they are not set.

Run dockerized pip as invoking user

---

index.js
package.json

Running "deploy function" is much faster if your serverless.yml and config hasn't changed, but the package it builds won't include requirements unless we hook into that event.
This adds the functionality to hook into the function deploy as well.

Build requirements for "deploy function" calls, too.

---

README.md
index.js

Retains support for 2.7. Adds note to README.
closes #24

Add support for Python3.6 on AWS.

---

README.md

Found that this plugin is no longer compatible with Serverless versions less than 1.12 due to lifecycle event changes that they made. Added note of this requirement to assist people pinned to older versions.
Before: https://github.com/serverless/serverless/blob/v1.11.0/lib/plugins/deploy/deploy.js
After: https://github.com/serverless/serverless/blob/v1.12.0/lib/plugins/deploy/deploy.js

Update README to reflect required Serverless version

---

README.md
index.js

This adds the ability to define the docker image to use for the build.

Add ability to define own Docker image (Issue 39)

---

index.js

Solves the issue of unnecessarily packaging libraries that are required but included by default by the cloud provider - such as boto3 by AWS. 
Done on a line-by-line basis by adding a #no-deploy comment beside the desired library in requirements.txt. Creates a parsed .requirements.txt file and re-targets pip install to that file.
example:
```
$ cat requirements.txt  
requests    
boto3 #no-deploy
pandas
```

Adds option to leave python libraries out of the deployment

---

README.md
index.js

This PR gives option to do `cleanup` on every `cleanup` lifecycle.
It's for users using frequently updating Python library, e.g. common local library which Lambda functions depend on.
closes #37

Add invalidateCaches option for frequently updating library.

---

index.js

This allows to add extra ``pip`` arguments. For example, I'm using this feature to enable the cache directory:
```
custom:
pythonRequirements:
dockerizePip: true
pipCmdExtraArgs:
- --cache-dir
- .requirements-cache
```
Let me know if the approach looks good (property naming, arguments as array).

[WIP] Add pipCmdExtraArgs property.

---

README.md
example/requirements.txt
example/serverless.yml
index.js
test.bats

Refactor deploy omittion. closes #57

---

README.md
index.js

allow custom python binary. closes #48

---

index.js

Before modification, there was meaningless line break.
Example:
```
Error --------------------------------------------------
Unable to link dependency 'hoge' because a file
by the same name exists in this service
```
I fixed it.
Example:
```
Error --------------------------------------------------
Unable to link dependency 'hoge' because a file by the same name exists in this service
```

Fix error message

---

index.js

The linux conditional options were being appended after the docker image had been declared, therefore breaking proper docker run syntax.

fix bug with docker when linux -u options are appended

---

index.js

We use a serverless variable to specify our package exclude list depending on some command line flags. Serverless variables are not yet resolved in the constructor of a plugin (see note [at the bottom of this](https://serverless.com/framework/docs/providers/aws/guide/plugins/#serverless-instance)), leading to the following error:
```
TypeError: this.serverless.service.package.exclude.push is not a function
at new ServerlessPythonRequirements (/Users/sumpfork/node_modules/serverless-python-requirements/index.js:311:45)
at PluginManager.addPlugin (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:51:28)
at plugins.forEach (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:91:14)
at Array.forEach (<anonymous>)
at PluginManager.loadPlugins …
```

Delay package exclude list manipulation

---

index.js
lib/pip.js
lib/pipenv.js

I needed this as a workaround for #85 . Might be useful for others too if they want more control whether or not they should use pipenv for generating the requirements.txt

Add a hidden option to enable/disable pipenv support.

---

lib/zip.js
test.bats

Refs #16
Similar to 6c5523c0cbe2c8af941eded308662d72e3e6decf

Create include array for zip step if undefined

---

example/.gitignore

To prevent accidental inclusion to a commit, ignore the install
directory and copied files created during local testing.

Ignore example generated files/directories

---

lib/pip.js
lib/pipenv.js

- Modify to strict comparison
- Remove unnecessary else

Fix according to other codes

---

unzip_requirements.py

We deploy our code to lambda in subdirectories. When importing `unzip_requirements.py` this results in `os.path.split(__file__)[0]` being empty, but `.requirements.zip` actually being higher up in the directory tree.
I believe it's valid to always assume that `.requirements.zip` is at the path pointed to by the env var `LAMBDA_TASK_ROOT` or else the current working dir for lambda, at least as long as the lambda code doesn't change this before imports? At least this works for our projects, subdirs or not.

assume .requirements.zip file is at lambda task root, fall back on the current directory

---

lib/pip.js

Fix docker volume bind path format, in order to support `Docker for Windows` when using sls/nodejs/docker from Powershell or from Windows Subsystem for Linux (WSL).
Issue #105

Fix Windows support for dockerizePip

---

lib/pip.js

Fix for requirements.txt is not copied to .serverless/requirements.txt when options.dockerizePip = true

Create .serverless folder if missing

---

lib/link.js

This change looks at the global package options for `individually=True`, which I use if I have multiple different languages for my functions and they all have different packaging rules. For example, I don't want node_modules in any python functions, or my .pyc/pyo/etc files in my nodejs functions. We can discriminate language easily based on the runtime of each function to decide what to do. 
With this check, we can now only add Python requirements to python function `include`s when `individually=True`

Handle multi-language projects

---

lib/link.js

I added it as a fallback, so the CI doesn't really test it. Mind testing it @nthienan? You can install this PR with:
```
npm install UnitedIncome/serverless-python-requirements#win32-cp
```

win32 copy fallback! closes #118

---

README.md
lib/pip.js

Add a `dockerSshSymlink` option which is a path to your .ssh folder containing your keys.
If the passphrase is empty, you will be able to package your private repos from the docker container.
Solves #69 ?

Add option to used private repos in requirements

---

README.md
lib/pip.js
package.json

Fix for PR #121 
The initial solution wasn't working due to docker being run as current user.
Docker is now run as root, so the ssh keys mounted in `/root/.ssh` are used, and it is possible to have private repos as requirements.
To still have correct ownership of the created `.serverless/requirements` folder, a `chown` command is run inside the docker container before exiting.
Other notes:
- Removed the `:z` flag when mounting the current directory, in order to be able to create the `.serverless/requirements` folder.
- Mounting the `.ssh/id_rsa` and `.ssh/known_hosts` instead of the whole directory because if you have a `.ssh/config` file, it will break ssh-agent inside the docker container due to restrictive file permission check.

Fix option to used private repos in requirements

---

README.md
index.js
lib/docker.js
lib/pip.js

Define the `dockerFile` option that is mutually exclusive with the `dockerImage` option.
If `dockerFile` is provided, it must be the name of the Dockerfile file, placed in the current directory.
When building requirements, a Docker image is built based on the provided Dockerfile, and requirements are then built using this image.
**Limitations:**
- built every time (even if image exists and Dockerfile has not changed)
- Dockerfile can have any name but MUST be in the current directory
**Open Questions:**
- If `dockerizePip` is false but any docker related options are provided, no warning are raised. Should I fix it?
- Are these limitations an issue? Do you have ideas how to improve on them?
**Related issues:**
- Closes #114
- Closes #126
- Closes #101 
- Closes #103

Add dockerFile option

---

lib/pip.js

The `error` of spawnSync's return value is an object of `Error`.
https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options

 Remove unnecessary `new Error()`

---

.editorconfig
.gitattributes

This makes it easier to develop on Windows and other IDEs by setting a standard for line breaks, spacing and encoding. Manual editing is required without this for `eslint` to pass.

set standards with .editorconfig and .gitattributes

---

unzip_requirements.py

Change logic to unzip into a temp directory and only move to the final
package directory on success.  This handles cases where Lambda kills the
container init halfway through, which seems to be a hard process kill
that never hits Python exception handlers.
Uses os.rename, since that is guaranteed to be atomic on Linux.
* Unzip to tempdir
* Make more logic lazy

Atomically create unzip_requirements package directory to handle partial failure

---

lib/pip.js

Instead of filtering later, just don't install them

Speed up requirements installation by skipping noDeploy

---

lib/docker.js

This fixes Docker Toolbox usage where the `-v C:/Users/...` syntax is not supported
It also tries really hard to find a working mount path no matter the platform combination
This should hopefully handle any corner case that we can ever come across

Support more bind path options

---

lib/pip.js

When using on Windows with the default docker configuration, it passes `.serverless\\requirements.txt` to `docker ... pip install ...`. This results in the following error:
```
Could not open requirements file: [Errno 22] Invalid argument: '.serverless\\requirements.txt'
```
To fix this, we can convert the paths from Windows style to Linux style when running on Windows with `dockerZip: true`.

Fix paths for Docker on Windows

---

lib/docker.js

My last change caused "Unable to find good bind path format" to be printed when Docker was not available or not running. That's not a very helpful message. Try running `docker version` and print the result if it failed for a better error message.

Better error message when Docker is not available

---

lib/clean.js
lib/pip.js

For function with Numpy / Scipy / etc. dependencies, we find the fact to zip your requirements to be a less optimal solution than including carefully stripped versions of these libraries.
Indeed, even with the zip option, you can easily reach 90Mo artefact, whereas by using stripped versions, and not even zipping the requirements, the same function's artefact is only 44Mo!
See also #153 for issues with the zipped requirements.
You just have to put in a folder the libraries you want to be included in your artefact, and to declare the path to this folder in your serverless.yml (at function level if you use individual packaging).
The process will use pip to download your dependencies as usual, but after that, it will copy the content from your vendor folder.
To prepare your vendors, you can …

Add vendors support

---

lib/pip.js

Per my issue [here](https://github.com/UnitedIncome/serverless-python-requirements/issues/184), fixed the bindPath to allow for white space.

Fixed bindPath so paths with white space will work.

---

test.bats
tests/base/package.json
tests/individually/package.json
tests/pipenv/package.json

* Add file to clean in test teardown
* Because git is displayed in an untracked file
* Fix package.json of test according to the current version
* Because it was displayed in `git diff`

Fix related to test

---

index.js
lib/clean.js
lib/inject.js
lib/pip.js
lib/zip.js

This PR fixes two issues I encountered while using `individually: true` option.
**1. Should package only the given function when invoked by `sls deploy function --function $FN_NAME`**
Suppose using `individually: true`. If you'd like to deploy a single function using `sls deploy function` command you'd expect the plugin to package only the module that contains the function specified. The current implementation, however, runs packaging for every module in `serverless.yml` definition, taking as much time as deploying all applications just to deploy a single function.
I simply added explicit `targetFuncs` property to filter target function if any specified in command line option.
**2. `moveModulesUp` should be called regardless of `zip` option**
When `individually: true`, each deployed …

Properly supporting `sls deploy function` command and zip option

---

lib/docker.js
lib/inject.js
lib/pip.js

This should fix the issue reported by @mrpgraae in #210.
I've also added support for `SLS_DEBUG` so we can more easily get some information on future errors.

Support serverless.yml and serverless.yaml in getBindPath()

---

README.md

Add custom Dockerfile workflow example

---

README.md
index.js
lib/pip.js
lib/slim.js
tests/base/_slimPatterns.yml
tests/pipenv/_slimPatterns.yml

Could you try this out @sweepy84? Install this branch with:
```
npm i UnitedIncome/serverless-python-requirements#pureish-js-slim
```
closes #212

clean up slim code using glob-all to make it more cross platform

---

lib/pip.js

Fixes #236
@vickeryj Can you please try this?
```
rm -Rf node_modules/serverless-python-requirements
npm i github:andrewfarley/serverless-python-requirements#bug-fix-requirements-ordering
```

Bugfix for requirements.txt options ordering

---

lib/pip.js

Fixes #242 
Could not use this plugin with any path that contains a space character due to missing/insufficient shell escaping/quoting.
I'm sorry I couldn't find a simple "quote-all" solution similar to what was in place pre-merge.  These solutions fall apart because certain things you can't quote or docker freaks out, for example features like the 'slim' would fall apart... eg: (see the last line)
```
[ '-m',
'pip',
'install',
'-t',
'\'/root/test me/serverless-python-requirements-farley/tests/base/.serverless/requirements\'',
'-r',
'\'/root/test me/serverless-python-requirements-farley/tests/base/.serverless/requirements/requirements.txt\'',
'" && find /root/test me/serverless-python-requirements-farley/tests/base/.serverless/requirements -name \\"*.so\\" -exec strip {} \';\'"' ]
```
The …

Bugfig, allowing all paths to have spaces

---

lib/pip.js

Fixes: #236 (again, properly)
Problem: requirements.txt options which must be in the proper order at the start of the file were being sorted.  This properly skips sorting them and keeps them in order they were.

Adding -f and -i to requirements.txt options ignore list before sorting

---

lib/pip.js

Current version seems to handle windows paths improperly
``` sh
docker: Error response from daemon: Mount denied:
The source path "C\\:/Users/Paul/Development/solidangle/match-api/app/.serverless/requirements\\:/var/task\\"
is not a valid Windows path.
See 'docker run --help'.
```
Calling `dockerPathForWin` on `bindPath` creation resolves issue.

fix broken windows path

---

lib/pip.js

This fixes #245 by making it so that relative paths in dependencies
resolve correctly
cc @AndrewFarley Just make your own PR with the tests & docker error based on this branch and i'll just merge yours.

Don't set pip CWD to target dir

---

lib/pip.js

Looking at the 1st time #184 was fixed, this should do the trick. Further evidence that #249 is really needed.
@rob-deans, could you try this out?
```
npm i unitedincome/serverless-python-requirements#win-path-spaces
```

attempt to fix #184

---

lib/pip.js

See #252 
Fixed a bug when loading requirements.txt on windows machines with dockerizePip set to false

fixed #252

---

appveyor.yml
index.js
lib/pip.js
package.json
test.bats
test.js
tests/base/package.json

Main advantage is that these can run on windows more easily, thus fixes #249 
cc @AndrewFarley @kichik @heri16

 First pass at tape tests instead of bats tests

---

circle.yml
lib/pip.js
test.bats
tests/base/serverless.yml

 honor escaped newlines in requirements.txt 

---

README.md
index.js
lib/pip.js

 Pass env vars to docker

---

README.md
appveyor.yml
index.js
lib/slim.js
package.json
test.bats
test.js
tests/base/serverless.yml
tests/pipenv/serverless.yml

override slimPatterns instead of appending

---

README.md
test.bats

Many editors clean up trailing white space on save. By removing it all
in one go, it helps keep future diffs cleaner by avoiding spurious white
space changes on unrelated lines.

Trim trailing white space throughout the project

---

lib/pip.js
lib/shared.js
test.js
tests/base/fn2/requirements.txt
tests/base/serverless.yml
tests/individually/module1/handler1.py

This PR fixes a weird bug, that wouldn't let you use a top-level `requirements.txt` alongside sub-module `requirement.txt`-files. 
The previous (I guess) unwanted behavior was, that when you had a root level function (i.e. `module: .`) with a `requirements.txt` and a second (sub-module) function (i.e. `module: my_submodule`) the first function didn't receive any requirements at all, whereas all requirements (from root and submodule) ended up in the artifact for function two:
<details>
see sample code: https://github.com/bweigel/serverless_playground/tree/293_weird_bug/sls_package
**`serverless.yml`**:
```yaml
service: packaging_test
plugins:
- serverless-python-requirements
provider:
name: aws
runtime: python3.6
region: eu-central-1
package:
individually: true
exclude:
- '**/*'
functions: …
```

Fixes weird bug, where root & submodule requirements weren't packaged correctly

---

unzip_requirements.py

This plugin not works sls invoke local.
```
Traceback (most recent call last):
File "/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/invoke.py", line 72, in <module>
module = import_module(args.handler_path.replace('/', '.'))
File "/Users/hiroshi.toyama/.pyenv/versions/3.6.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 994, in _gcd_import
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", …
```

fix sls invoke local not works.

---

lib/pipenv.js

Remove editableFlag from .serverless/requirements.txt when using Pipfile.
Based on [#314 (comment)](https://github.com/UnitedIncome/serverless-python-requirements/issues/314)
closes #314

Support editable packages with Pipfile.

---

README.md
lib/slim.js

As #318 and [#216 - comment](
https://github.com/UnitedIncome/serverless-python-requirements/issues/216#issuecomment-419037475) note, stripping `*.so` files can mess things up on Lambda, even when done in Docker.
For example, this is the error you will get if you strip opencv: `ImportError: /tmp/sls-py-req/cv2/cv2.cpython-36m-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned`
In these cases, it is useful to simply turn off stripping while retaining the other behaviors of `slim: true`.

Option to turn off binary file stripping when when using `slim: true`

---

lib/pip.js
lib/shared.js
package.json
test.js

Currently, `serverless-python-requirements`  does not work in our environment because this library is using md5. This algorithm is not FIPS compliant. We are getting the following error: 
`digital envelope routines:EVP_DigestInit_ex:disabled for fips`
I created this PR so that we can move away from using md5 and use sha256 algorithm which is FIPS compliant.

use sha256 instead of md5

---

circle.yml
lib/inject.js
lib/zipTree.js
test.js

Fixes https://github.com/UnitedIncome/serverless-python-requirements/issues/233

Preserve binary file permissions in zip

---

lib/poetry.js
package.json
test.js
tests/non_build_pyproject/.gitignore
tests/non_build_pyproject/handler.py
tests/non_build_pyproject/package.json
tests/non_build_pyproject/pyproject.toml
tests/non_build_pyproject/requirements.txt
tests/non_build_pyproject/serverless.yml

Why:
* The pyproject.toml file is for more than just poetry.
This change addresses the need by:
* Add test for use case where pyproject.toml is only used for black.
* Add toml parser to package.json.
* Update poetry.js to base poetry usage on whether or not the build
system requires it.
Fixes: #324

Parse pyproject.toml to determine poetry use.

---

README.md
lib/pip.js

Using junctions and adding a negative include pattern massively speed up the packaging time

Speed up windows packaging

---

README.md

Fixes lamba -> lambda in the readme file.

docs: fix minor typo in readme

---

README.md
appveyor.yml
index.js
test.js
tests/base/requirements-w-hashes.txt

Closes #304 
Based on https://github.com/UnitedIncome/serverless-python-requirements/issues/304#issuecomment-454787377 I changed the default for `noDeploy` to an empty array. Not entirely sure if it might have been enough to remove `boto3` and `botocore` instead.

Default `noDeploy` to an empty list

---

README.md
index.js
lib/docker.js
lib/pip.js

These changes allow arbitrary arguments to be passed to the `docker build` step and `docker run` step in the dockerized pip install case through through the creation of 2 new options: `dockerBuildCmdExtraArgs` and `dockerRunCmdExtraArgs`, respectively.
Both new options accept arrays of strings to be pushed onto the docker command argument arrays.
This is necessary to be able to pass Docker build arguments to the image build step, as well as to be able to attach volumes which may be referenced by the use of a `file://`-style entry in `requirements.txt`.

Allow arbitrary extra args to be passed to docker build and dockerized pip install steps

---

package.json

Fixes warning of the form:
[warn] { parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.

Set prettier parser to "babel" to fix lint warning

---

README.md
index.js
lib/pip.js

This allows native OS libraries (`*.so` files) to be copied to the
serverless archive to be available at runtime. This introduces the new
option `dockerExtraFiles`, a list of paths on the Docker image to copy.
For example, the `mysqlclient` package requires
`libmysqlclient.so.1020`. One can now add an item to the
`dockerExtraFiles` option in their `serverless.yml`:
pythonRequirements:
dockerExtraFiles:
- /usr/lib64/mysql57/libmysqlclient.so.1020
This file will be available at runtime in the Lambda function.
This removes the need to manage these files in a more manual way and
avoids the need to commit binary files one's repository.

Add support to copy extra files from the Docker image to the package

---

README.md
lib/pip.js
lib/poetry.js
test.js
tests/poetry/poetry.lock
tests/poetry/pyproject.toml

This is just a copy of #362, but with tests fixed.

Fix poetry with git dependencies

---

lib/poetry.js
test.js

The `export` command for poetry 1.0.0b1 outputs to standard output if the `-o` option is not specified.
Modified to use `spawnSync` return values.

Fix poetry 1.0.0b1 export prints to stdout by default

---

lib/inject.js
test.js

Modify the following to prevent modification of the serverless deploy package file hash.
+ Inserting packages asynchronously changes the order
+ The timestamp is changed when creating a folder in the package zip file with `jszip`
Changing the file hash will cause unnecessary deployment.
I'm sorry my English is not good.

Prevent serverless package hash from changing

---

lib/pip.js

My serverless.yml file looks like:
```
pythonRequirements:
pythonBin: ".venv/bin/python3"
invalidateCaches: true
pipCmdExtraArgs:
- "--trusted-host pypi.python.org"
- "--trusted-host pypi.org"
- "--trusted-host files.pythonhosted.org"
```
Before this change, the generated `pipCmds` looked like:
```
pipCmds: [
[
'.venv/bin/python3',
'-m',
'pip',
'install',
'--trusted-host pypi.python.org',
'--trusted-host pypi.org',
'--trusted-host files.pythonhosted.org',
'-t',
'~/Library/Caches/serverless-python-requirements/01dde858536f71d67120395d14566ab6f37cce626069dc5d99d750fcd314e5c2_slspyc',
'-r',
'~/Library/Caches/serverless-python-requirements/01dde858536f71d67120395d14566ab6f37cce626069dc5d99d750fcd314e5c2_slspyc/requirements.txt',
'--cache-dir', …
```

Expand pip commands into separate entries

---

README.md

Poetry has released multiple 1.x versions now: https://github.com/python-poetry/poetry/tree/1.0.3

Remove outdated note about poetry 1.0

---

README.md
lib/poetry.js

Hi, Here is the first attempt at fixing the change in the poetry export command.
The change needed was detailed here: [https://python-poetry.org/docs/cli/#export](url)

Change to poetry command to export requirements.txt resolving #445

---

appveyor.yml
circle.yml
lib/pip.js
lib/poetry.js
package.json
test.js

This started as a simple version update, but I found more things that needed fixing before we can get back to a full CI run again.
Please review by commit.

chore(ci): get CI working again

---

lib/inject.js

The existing regex had the side effect of matching python files
from other modules if their filename or path happened to contain
the string `s_`.

Correct imprecise regex in moveModuleUp function (fixes #444)

---

circle.yml
test.js

In #282 the test suite was ported from BATS to TAPE.

chore(ci): remove bats testing references

---

README.md

Using MarkdownLint in VSCode, this file was showing many linter errors,
mostly around whitespace issues, but a few others that made it annoying
enough when looking at the file, it was inconsistent and difficult to
read.
Also handles a few existing notes about caching.
Refs #412
Resolves #420
Resolves #424

docs: update readme style

---

tests/base/serverless.yml
tests/individually/serverless.yml

The fixture tests files were raising a couple of warnings on incorrect
YAML structure, based on the Serverless IDE:
https://github.com/threadheap/serverless-ide-vscode/blob/054264da94ed17c42e6e3ba0dd662bd00114e05b/packages/serverless-framework-schema/json/aws/common/runtime.json
https://github.com/threadheap/serverless-ide-vscode/blob/631165a6b5a928ef8f59ba9361af3c6b79a8c38d/packages/serverless-framework-schema/json/common/package-config.json#L13-L19

chore(test): update fixture serverless.yml syntax

---

test.js

The executable permissions set in the tests modified should be 755 to work in a zip file. 775 is okay, but the group write gets dropped, which was not what the test was checking.

Correct tests failing in master

---

.github/workflows/test.yml
index.js

This will fix https://github.com/serverless/serverless/issues/6752 and https://github.com/UnitedIncome/serverless-python-requirements/issues/414

Fix single function deployment

---

lib/pip.js
test.js
tests/base/requirements-w-editable.txt

This PR addresses two issues:
* All requirements flags (-i, -e, -c, -f, -r) are handled and no longer silently ignored. This fixes https://github.com/UnitedIncome/serverless-python-requirements/issues/36
* It also strips out -e flags, but preserves the requirement itself, as there were various issues with different python and pip version for editable requirements. This fixes https://github.com/UnitedIncome/serverless-python-requirements/issues/240
I have also added an additional test patch that verifies this behavior.

Handle all requirement flags properly and strip -e flags

---

tests/base/requirements.txt

Failing tests on `master` branch were caused by the fact that dependencies that were used were not pinned to specific versions. In the meantime, `Flask` has two major releases, with the last one (2.x) also included a bump in one of the dependencies (Werkzeug), that in newer version depends on `dataclasses` for Python3.6, which interfered in tests that were checking that `dataclasses` library should not be bundled. Pinned down version of `Flask` does not depend on `Werkzeug` that requires `dataclasses` library

test: Pin dependencies to avoid unexpected upgrades

---

index.js

`cli.generateCommandsHelp` was removed with some of the Framework refactors. So currently `sls requirements` produces a programmer error.
This patch fixes the command, with a fallback to old Framework version where `generateCommandsHelp` will remain to be used

Fix help output for `requirements` container command

---

.github/workflows/test.yml
lib/zip.js
package.json
tests/base/serverless.yml
tests/individually/serverless.yml
tests/non_build_pyproject/serverless.yml
tests/non_poetry_pyproject/serverless.yml
tests/pipenv/serverless.yml
tests/poetry/serverless.yml

Ensure that ahead of `v3` Framework release, plugin supports `package.patterns` notation.
@medikoo Due to an inference between `patterns` and `include` when wide exclusions are concerned (`!src/*` and similar) I had to make this a breaking change. Only other option would be to go back to version inspection. Please let me know what do you think :bow:

fix(Packaging): Ensure plugin supports `package.patterns` notation

---

index.js

defines the module property to remove the validation error in serverless 2.0+ 
ref: https://github.com/serverless/serverless-python-requirements/pull/575

feat: Introduce schema validation for `module` property

---

lib/docker.js
lib/pip.js
lib/pipenv.js
lib/poetry.js
package.json

Related to: https://github.com/serverless/serverless-python-requirements/pull/646 - sync use of spawn prevented interactive output to be updated

refactor: Adapt to `async` version of `spawn`

---

index.js
lib/clean.js
lib/docker.js
lib/inject.js
lib/layer.js
lib/pip.js
lib/pipenv.js
lib/poetry.js
lib/shared.js
lib/zip.js

Configured in a way that would allow support both for v2 and v3 versions of the Framework

Add modern logs for Serverless Framework v3

---

lib/docker.js
lib/pip.js
lib/pipenv.js
lib/poetry.js

Use dedicated Error class from the Framework

---

lib/docker.js

Ensure proper cast to string before `trim` call as reported in: https://github.com/serverless/serverless-python-requirements/pull/648#issuecomment-984840164

fix: Ensure cast `toString` before `trim` on buffer

---

lib/docker.js

This change solves the problem [#371](https://github.com/serverless/serverless-python-requirements/issues/371) that is occurring in wsl2.
In order to make wsl2 work as well as linux, the wsl decision was changed so that it only applies to wsl1.

fix: Address unknown path format error in `wsl2`

---

test.js
tests/base/serverless.yml
tests/individually/serverless.yml
tests/pipenv/serverless.yml
tests/poetry/serverless.yml

Hey, 
I wanted to work on a different feature, but to my surprise most of the tests were failing on an unmodified fork. That's because I was using latest version of Serverless and the tests are full of CLI arguments which are now deprecated. Here's a small trick that makes the tests valid again without having to modify all the functions.
I also think [getting rid of the python2.7 tests](https://github.com/serverless/serverless-python-requirements/pull/603) is a good idea.

test: Refactor tests to use `env` instead of `opt` vars

---

.github/workflows/integrate.yml
.github/workflows/validate.yml
test.js

Python2.7 is EOL for a long time and e.g. AWS doesn't support that runtime for a very long time. The support should still be there for esoteric use cases, but this PR drops test coverage for Python 2.7.

test: Remove tests against python2.7

---

lib/pip.js
test.js

Improve how we expose an error when docker command fails. Now it should provide more actionable information to users. 
Closes: #702

refactor: Improve error message for docker failures

---

README.md

This pull request adds a warning regarding the lack of support of the individual packaging feature for modules that use Pipenv or Poetry.
#341 could take time before being merged and support for Poetry could arrive even later, in the meanwhile we should at least warn users about it.
Relates to https://github.com/UnitedIncome/serverless-python-requirements/issues/268.

docs: Add a warning about individual packaging with Poetry/Pipenv

---

README.md
index.js
lib/poetry.js
test.js
tests/poetry/serverless.yml

* Distinct logging whether the requirements.txt file is generated from poetry.lock vs pyproject.toml.
* New boolean flag: requirePoetryLockFile - When set to true, fail the build when poetry.lock is missing. This helps with creating reproducible builds where you want to have a fixed poetry.lock file instead of one generated on the fly.
Follow up to https://github.com/serverless/serverless-python-requirements/pull/639

feat: Introduce `requirePoetryLockFile` flag

---

index.js

BREAKING CHANGE: Switches to official AWS docker images from previous `lambci` images that did not support Python 3.9
Switch to official images as defaults for packaging with Docker. Please note that it's a breaking change and will be released as a part of next major version of the plugin. 
Closes: #647

feat: Switch to official AWS docker images by default

---

README.md
index.js
lib/poetry.js
test.js
tests/poetry_packages/_poetryGroups.yml
tests/poetry_packages/_slimPatterns.yml
tests/poetry_packages/handler.py
tests/poetry_packages/package.json
tests/poetry_packages/pyproject.toml
tests/poetry_packages/serverless.yml

Poetry 1.2+ allows to create custom dependency groups in `pyproject.toml`. However, the [`export`](https://github.com/python-poetry/poetry-plugin-export) plugin (unlike the `install` command) does not include those dependencies by default, even if they're not marked as optional, resulting in them being missing from the Serverless deployment package. This PR introduces three new configuration parameters that directly wrap Poetry's `--with`, `--without` and `--only` parameters and allow to include dependencies from those missing groups in the exported `requirements.txt` file.

Add support for specifying custom dependency groups in Poetry

---

.github/workflows/integrate.yml
.github/workflows/validate.yml
README.md
lib/pipenv.js
package.json

Plugin v6 now requires `pipenv` >= 2022.8.13 (https://github.com/serverless/serverless-python-requirements/pull/718)
This PR will allow users to upgrade to v6 without also requiring the latest `pipenv`.

fix: Add legacy `pipenv` backward compatability

---

.github/workflows/integrate.yml

Matrix values appear to mistakenly added to `tagIfNewVersion` instead of `linuxNode12`

fix: Fix integration test matrix configuration

---

.github/workflows/validate.yml
lib/pipenv.js
tests/base/package.json
tests/individually/package.json
tests/non_build_pyproject/package.json
tests/non_poetry_pyproject/package.json
tests/pipenv/package.json
tests/poetry/package.json
tests/poetry_individually/package.json

Removes use of the now-removed flag `--keep-outdated` on pipenv lock.  See [pipenv 2023.7.9 release notes](https://github.com/pypa/pipenv/releases/tag/v2023.7.9).
Rather than re-generating or potentially updating a user's Pipenv.lock file, it'll go straight into trying to build the requirements file.
The pre-existing behavior was that if the Pipfile.lock file was missing, that the plugin will generate one.  Since this is likely undesireable, added a warning log message pointing a user to the Pipenv documenation on how to address it.
Also updates github-actions test matrix to include the before/after of this pipenv behavior change.
Closes: #779

fix: Remove outdated Pipenv requirements flag

---

test.js

Temporary disable cache-related tests as for some reason they're failing on CI (they're executing correctly locally), to unblock release. They will be turned back after investigation

ci: Temp skip of cache-related tests

---

.github/workflows/integrate.yml

In order to unblock release `v6.0.1`
Related: #798

ci: Temporarily disable test run on integrate

---

README.md

The cleanCache command should be documented in README, see https://github.com/serverless/serverless-python-requirements/issues/437#issuecomment-1155659925
This doesn't fix issue #437 -- but it makes the workaround more visible.
Move commands from inline code markdown to code blocks to make them more visible.

Document cleanCache in README

---

lib/pip.js

This should help with this issue: https://github.com/serverless/serverless-python-requirements/issues/663
Currently, if pip fails, you just get a "Exited with code 1" that is entirely unhelpful and leads to people thinking they have other issues than dependency. 
With this fix, it will spit out the error (if there is one)

Fix for spitting error out when pip fails

---

tests/base/serverless.yml

I was getting invalid runtime errors with the code in place. it looks like node8.10 has been removed from support for serverless (/aws). This bumps the version up to nodejs14.x for the one serverless function that defined it
Warning: Invalid configuration encountered
at 'functions.hello3.runtime': must be equal to one of the allowed values [dotnet6, go1.x, java17, java11, java8, java8.al2, nodejs14.x, nodejs16.x, nodejs18.x, nodejs20.x, provided, provided.al2, provided.al2023, python3.7, python3.8, python3.9, python3.10, python3.11, ruby2.7, ruby3.2]

Bumped node version as it was giving sls errors

---

index.js
lib/pip.js

resolve: #817 
Add feature flag `dockerRootless` and default value `false`. 
Change `lib/pip.js` file permission change logic for supporting docker rootless environment. 
I think that its better add some document about this in `README.md`

Add docker rootless feature flag and its implementation for supporting docke rootless environment
